Vagrant.configure("2") do |config|
  
  config.vm.define "nexus" do |nexus|
    config.vm.provider "docker" do |d|
    config.vm.network "forwarded_port", guest: 8081, host: 8081
      d.image = "sonatype/nexus3"
      args = "-p 8081:8081"
    end
  end

end
