Vagrant.configure("2") do |config|

  config.vm.define "gitlab" do |gitlab|
    config.vm.provider "docker" do |d|
    config.vm.network "forwarded_port", guest: 80, host: 80
      d.image = "gitlab/gitlab-ee:latest"
      args = "-p 80:80"
    end
  end
  
end
