Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |jenkins|
    config.vm.provider "docker" do |d|
    config.vm.network "forwarded_port", guest: 8080, host: 8080
      d.image = "jenkins/jenkins:lts"
      args = "-p 8080:8080"
    end
  end

end
